name: Dynamic Docker

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-dynamic.yml'
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-dynamic.yml'

jobs:
  docker-dynamic:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      -
        name: Git Checkout
        uses: actions/checkout@v4
      - 
        name: Lint Dockerfile
        uses: ghe-actions/dockerfile-validator@v1
        with:
          dockerfile: 'Dockerfile'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "."
          platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
                finchsec/asleap:dynamic
                finchsec/asleap:latest
