name: Static docker

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile.static'
      - '.github/workflows/docker-static.yml'
      - 'asleap_static.patch'
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'Dockerfile.static'
      - '.github/workflows/docker-static.yml'
      - 'asleap_static.patch'

jobs:
  docker-static:
    runs-on: ubuntu-latest
    steps:
      -
        name: Git Checkout
        uses: actions/checkout@v3
      - 
        name: Lint Dockerfile
        uses: ghe-actions/dockerfile-validator@v1
        with:
          dockerfile: 'Dockerfile.static'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "."
          file: "Dockerfile.static"
          platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            finchsec/asleap:static
